import Head from "next/head";
import { Navigation } from "../../components/Common";
import Link from "next/link";

export default function Onboarding() {
  return (
    <div>
      <Head>
        <title>BeatBlox - Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <section className="section-onboarding d-flex align-items-center py-5 py-md-0">
        <div className="container py-5">
          <div className="d-flex flex-column py-5">
            <div className="row py-5 my-3 d-block d-md-none"></div>
            <div className="row text-center pt-5">
              <div className="col-12">
                <h1 className="onboarding-title">
                  BeatBlox<span className="text-outline"> onboarding</span>
                </h1>
              </div>
            </div>
            <div className="row px-5 px-md-0">
              <div className="col-md-4 text-center mt-5">
                <img
                  className="img-fluid  d-block mx-auto"
                  src="/images/onboarding/icon-perform.svg"
                ></img>
                <Link href="/onboarding/perform-in-the-metaverse">
                  <a className="btn btn-lg btn-outline-light rounded-pill mt-5">
                    Perform
                  </a>
                </Link>
                <h5 className="pt-5 text-muted">
                  Schedule your date to play at the metaverse. Be part of -- &
                  discover new ways fo interaction.
                </h5>
              </div>
              <div className="col-md-4 text-center mt-5">
                <img
                  className="img-fluid d-block mx-auto"
                  src="/images/onboarding/icon-catalog.svg"
                ></img>
                <Link href="/onboarding/join-our-catalog">
                  <a className="btn btn-lg btn-outline-light rounded-pill mt-5">
                    Join us
                  </a>
                </Link>
                <h5 className="pt-5 px-3 text-muted">
                  Join our catalog and become part of the #BeatBloxArtists.
                </h5>
              </div>
              <div className="col-md-4 text-center mt-5">
                <img
                  className="img-fluid  d-block mx-auto"
                  src="/images/onboarding/icon-huts.svg"
                ></img>
                <Link href="/onboarding/have-your-spot-in-our-district">
                  <a className="btn btn-lg btn-outline-light rounded-pill mt-5">
                    Build with us
                  </a>
                </Link>
                <h5 className="pt-5 px-3 text-muted">
                  Get the opportunity to be part of our district at Decentraland
                  by renting a hut for your own
                </h5>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
