import Head from "next/head";
import Image from "next/image";
import Link from 'next/link';
import styles from "../styles/Faq.module.css";
import { Navbar, Nav, Container, Row, Col, Tab } from "react-bootstrap";

export default function auctionHouse() {
  return (
    <div className={styles.container}>
      <Head>
        <title>BeatBlox - Auction House</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        variant="dark"
        fixed="top"
        expand="lg"
        className="py-5 px-5 px-md-0"
      >
        <Container>
          <Navbar.Brand href="/">
            <img src="/images/logo.svg" alt="" />
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto my-2 my-lg-0">
              <Nav.Link href="#">
                <u>Auction House</u>
              </Nav.Link>
              <Nav.Link href="/">Back Home</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <div className="video-swiper w-100">
        <video
          autoPlay={true}
          controls={false}
          loop
          muted
          src="/videos/auction-house.mp4"
          type="video/mp4">
        </video>
      </div>
      <div className="main-swiper h-100 w-100 d-flex align-items-center">
        <div className="container d-flex justify-content-center">
          <div className="row h-100 px-5 px-md-0 d-flex align-items-center">
            <div className="col-12 text-center">
              <h4>
                Coming Soon
              </h4>
              <p className="mt-4 text-muted">
                Get your early access to our closed Beta Auction House
              </p>
              <Link href="/">
                <a className="btn btn-lg btn-outline-light rounded-pill mt-4">Get yours!</a>
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
