import React, { useState, useEffect } from "react";
import Head from "next/head";
import Link from 'next/link';
import { ethers, utils } from "ethers";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, Autoplay } from "swiper";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import { Modal, Button } from "react-bootstrap";
import Earlysup from "../utils/Earlysup.json";
const CONTRACT_ADDRESS = "0xd3A3F2Be9FB936479ed5370D085bA4b6f1e29487";
const contractABI = Earlysup.abi;
import { Navbar, Nav, Container, Row, Col, Tab } from "react-bootstrap";

const Collection = () => {

  const [balance, setBalance] = useState(0);
  const [currentAccount, setCurrentAccount] = useState(0);

  useEffect(() => {
    checkIfWalletIsConnected();
  }, []);

  const checkIfWalletIsConnected = async () => {
    try {
      const { ethereum } = window;
      if (!ethereum) {
        //alert("Make sure you have metamask!");
        return;
      } else {
        //console.log("We have the ethereum object", ethereum);
      }

      const accounts = await ethereum.request({
        method: "eth_accounts"
      });

      if (accounts.length !== 0) {
        const account = accounts[0];
        setCurrentAccount(account);
        const provider = new ethers.providers.Web3Provider(ethereum)
        const signer = provider.getSigner()
        const connectedContract = new ethers.Contract(CONTRACT_ADDRESS, contractABI, signer)
        const address = await signer.getAddress();
        const balance = await connectedContract.balanceOf(address);
        console.log(balance.toString());
        setBalance(balance.toString());
      } else {
        // shows connect wallet button
      }
    } catch (error) {
      console.log(new Error(error));
    }
  };

  return (
    <div className="h-100">
      <Head>
        <title>BeatBlox - My Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar
        variant="dark"
        fixed="top"
        expand="lg"
        className="py-5 px-5 px-md-0"
      >
        <Container>
          <Navbar.Brand href="/">
            <img src="/images/logo.svg" alt="" />
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto my-2 my-lg-0">
              <Nav.Link href="#">
                <u>Collection</u>
              </Nav.Link>
              <Nav.Link href="/">Back Home</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <div className="d-flex align-items-center h-100">
        <div className="container">
          <div className="row section h-100 p-5 text-center align-items-center">
            { balance === 0 && (
              <div className="col-10 mx-auto">
                <h4>You don't have any Early Supporter Token</h4>
                  <p className="mt-4 text-muted text-center">
                  Get your early access to our closed Beta Auction House
                </p>
                <Link href="/">
                  <a className="btn btn-lg btn-outline-light rounded-pill mt-4">
                    Back Home
                  </a>
                </Link>
              </div>
            )}
            { balance > 0 && (
              <>
                <div className="row">
                  <div className="col-8 rounded-3 border col-md-4 mx-auto">
                    <video
                      autoPlay={true}
                      controls={false}
                      loop
                      muted
                      width="100"
                      src="/videos/early-supporters-square.mp4"
                      type="video/mp4">
                    </video>
                  </div>
                </div>
                <div className="row">
                  <h4 className="text-center mt-4">You have <b>{balance}</b> Early Supporters Token</h4>
                </div>
              </>
            )}
          </div>
        </div> 
      </div>
    </div>
  );
};

export default Collection;
