import Head from 'next/head'
import Link from 'next/link'
import { useState, useEffect } from 'react';
import styles from '../styles/Home.module.css';
import Navigation from '../components/Navigation';
import About from '../components/About';
import Player from '../components/Player';
import Marketplace from '../components/Marketplace';
import Onboarding from '../components/Onboarding';
import Features from '../components/Features';
import Roadmap from '../components/Roadmap';
import Contact from '../components/Contact';
import Minting from '../components/Minting';
import Footer from '../components/Footer';
import Team from '../components/Team';
import News from '../components/News';
import { Swiper, SwiperSlide } from 'swiper/react';
import { Pagination, A11y, Mousewheel, EffectFade, Controller } from 'swiper';
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/mousewheel';
import 'swiper/css/effect-fade';
import { Navbar, Nav, Container, Modal } from 'react-bootstrap';
import { isMobile } from "react-device-detect";
import District from '../components/District';

export default function Home () {

  const [controlledSwiper, setControlledSwiper] = useState(null);
  const [mainSwiper, setMainSwiper] = useState();
  const [show, setShow] = useState(false);
  const handleClose = () => setShow(false);
  const handleShow = () => setShow(true);
  const [loadCount, setLoadCount] = useState(0);

  return (
    <div className={styles.container}>
      <Head>
        <title>BeatBlox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
      <About/>
      <Player/>
      <Marketplace/>
      <District/>
      <Onboarding/>
      <Roadmap/>
      <Team/>
      <News/>
      <Footer/>

      <div className="bottomNav py-3 px-5 px-md-0 d-none d-md-flex">
        <div className='container d-flex justify-content-between py-5'>
          <Modal
            show={show}
            onHide={handleClose}
            size="lg"
            aria-labelledby="contained-modal-title-vcenter"
            centered
          >
            <Modal.Body className="p-0">
              <div className="embed-container">
                <iframe src="https://player.vimeo.com/video/652685945?h=0fe6572dd5" frameBorder="0" allow="autoplay; fullscreen; picture-in-picture" allowFullScreen></iframe>
              </div>
            </Modal.Body>
          </Modal>
        </div>
      </div>
    </div>
  )
}