import Head from 'next/head'
import { useEffect, useState } from 'react';
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import About from '../components/About';
import Features from '../components/Features';
import Roadmap from '../components/Roadmap';
import Contact from '../components/Contact';
import Benefits from '../components/Benefits';
import Team from '../components/Team';
import { Swiper, SwiperSlide, useSwiper } from 'swiper/react';
import { Pagination, A11y, Mousewheel, EffectFade, Controller } from 'swiper';
import 'swiper/css';
import 'swiper/css/pagination';
import 'swiper/css/mousewheel';
import 'swiper/css/effect-fade';
import { Navbar, Nav, Container } from 'react-bootstrap';


export default function Home () {
  
  const [controlledSwiper, setControlledSwiper] = useState(null);
  const [mainSwiper, setMainSwiper] = useState();

  return (
    <div className={styles.container}>
      <Head>
        <title>BeatBlox</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar variant="dark" fixed="top" expand="lg" className="py-5 px-5 px-md-0">
        <Container>
          <Navbar.Brand href="#home">
            <img src="/images/logo.svg" alt=""/>
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto my-2 my-lg-0">
              <Nav.Link href="#" onClick={() => mainSwiper.slideTo(0)}>About Us</Nav.Link>
              <Nav.Link href="#" onClick={() => mainSwiper.slideTo(3)}>Roadmap</Nav.Link>
              <Nav.Link href="#">Decentraland</Nav.Link>
              <Nav.Link href="#">Auction House</Nav.Link>
              <Nav.Link href="/faqs">FAQs</Nav.Link>
              <Nav.Link className="btn btn-light text-dark rounded-pill" href="#" onClick={() => mainSwiper.slideTo(2)}>Early Supporters NFT</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <Swiper
        modules={[Pagination, A11y, Mousewheel, Controller]}
        spaceBetween={0}
        slidesPerView={1}
        direction={"vertical"}
        mousewheel={true}
        pagination={{ clickable: true }}
        scrollbar={{ draggable: true }}
        onSwiper={(swiper) => setMainSwiper(swiper)}
        onSlideChange={() => console.log('slide change')}
        className="main-swiper"
        controller={{ control: controlledSwiper }}
        speed={800}
      >
        <SwiperSlide><About mainSwiper={mainSwiper}/></SwiperSlide>
        <SwiperSlide><Features/></SwiperSlide>
        <SwiperSlide><Benefits/></SwiperSlide>
        <SwiperSlide><Roadmap/></SwiperSlide>
        <SwiperSlide><Contact/></SwiperSlide>
        <SwiperSlide><Team/></SwiperSlide>
      </Swiper>

      <Swiper
        spaceBetween={0}
        effect={"fade"}
        modules={[EffectFade, Controller]}
        className="video-swiper"
        onSwiper={setControlledSwiper}
      >
        <SwiperSlide>
          <video
            autoPlay={true}
            controls={false}
            loop
            muted
            src="/videos/about.mp4"
            type="video/mp4">
          </video>
        </SwiperSlide>
        <SwiperSlide>
          <video
            autoPlay={true}
            controls={false}
            loop
            muted
            src="/videos/features.mp4"
            type="video/mp4">
          </video>
        </SwiperSlide>
        <SwiperSlide>
          <video
            autoPlay={true}
            controls={false}
            loop
            muted
            src="/videos/early-supporters.mp4"
            type="video/mp4">
          </video>
        </SwiperSlide>
        <SwiperSlide>
          <video
            autoPlay={true}
            controls={false}
            loop
            muted
            src="/videos/roadmap.mp4"
            type="video/mp4">
          </video>
        </SwiperSlide>
        <SwiperSlide>
          <video
            autoPlay={true}
            controls={false}
            loop
            muted
            src="/videos/contact.mp4"
            type="video/mp4">
          </video>
        </SwiperSlide>
        <SwiperSlide>
          <video
            autoPlay={true}
            controls={false}
            loop
            muted
            src="/videos/team.mp4"
            type="video/mp4">
          </video>
        </SwiperSlide>
      </Swiper>
      <div className="bottomNav py-3 px-5 px-md-0">
        <div className='container d-flex justify-content-between py-5'>
          <div>
            <button className="btn btn-outline-light rounded-pill">Video</button>
          </div>
          <div>
            <button className="btn btn-outline-light rounded-pill btn-icon btn-music">
              <img src="/images/music.svg"/>
            </button>
            <a href="https://discord.gg/fQR74Z8S" target="_blank" rel="noreferrer" className="btn btn-outline-light rounded-pill btn-icon ml-1">
              <img src="/images/discord.svg"/>
              Discord
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}