import Head from "next/head";
import styles from "../styles/Faq.module.css";
import Iframe from 'react-iframe'

export default function liveStreaming() {
  return (
    <div className="h-100">
      <Head>
        <title>BeatBlox - Live Streaming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Iframe url="https://iframe.videodelivery.net/f84cbd14ca7191d5cf63a24ec6fe6552"
        width="100%"
        height="100%"
        id="myId"
        className="myClassname"
        display="initial"
        position="relative"
        styles={{width: "100%", height: "auto"}}/>
    </div>
  );
}
