import Head from 'next/head'
import { useState } from 'react';
import styles from '../styles/Faq.module.css';
import { Navbar, Nav, Container } from 'react-bootstrap';


export default function Onboarding () {
  const [name, setName] = useState('');
  const [email, setEmail] = useState('');
  const [track, setTrack] = useState('');
  const [message, setMessage] = useState('');

  const handleSubmit = e => {
    e.preventDefault();
    const data = {
      name,
      email,
      track,
      message,
    };
    fetch('/api/contact', {
      method: 'post',
      body: JSON.stringify(data),
    });
    console.log(data);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>BeatBlox - Onboarding</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar variant="dark" fixed="top" expand="lg" className="py-5 px-5 px-md-0">
        <Container>
          <Navbar.Brand href="/">
            <img src="/images/logo.svg" alt=""/>
          </Navbar.Brand>
          <Navbar.Toggle aria-controls="basic-navbar-nav" />
          <Navbar.Collapse id="basic-navbar-nav">
            <Nav className="ms-auto my-2 my-lg-0">
              <Nav.Link href="#"><u>On-Boarding</u></Nav.Link>
              <Nav.Link href="/">Back Home</Nav.Link>
            </Nav>
          </Navbar.Collapse>
        </Container>
      </Navbar>
      <div className="container not-fullscreen">
        <div className="row px-5 px-md-0">
          <div className="col-12 col-md-6">
            <h2>Welcome to the BeatBlox On-Boarding Process.</h2>
            <h3>First of all, please read the following documents:</h3>
            <a href="https://www.surveymonkey.com/r/3DT35YJ" target="_blank" rel="noreferrer" className="btn btn-lg btn-outline-light rounded-pill mt-4">
              01. Benefits
            </a><br/>
            <a href="https://www.surveymonkey.com/r/3DT35YJ" target="_blank" rel="noreferrer" className="btn btn-lg btn-outline-light rounded-pill mt-4">
              02. Artist Dossier
            </a><br/>
            <a href="https://www.surveymonkey.com/r/3DT35YJ" target="_blank" rel="noreferrer" className="btn btn-lg btn-outline-light rounded-pill mt-4">
              03. NFT Description
            </a>
            <p className="mt-4">
              In case you have any further question pleaee feel free to contact us to onboarding@beatblox.org.<br/><br/>
              Please do have in mind that our catalog is curated so if you would like to submit your work please fill the following form:
            </p>
          </div>
        </div>
        <div className="row">
          <div className="col-12 col-md-6 pt-3">
            <form onSubmit={handleSubmit}>
              <div className="mb-3">
                <input
                  type="text"
                  placeholder="Name"
                  className="form-control rounded-0 border-0 border-bottom border-white"
                  aria-describedby="emailHelp"
                  onChange={e => setName(e.target.value)}
                />
              </div>
              <div className="mb-3">
                <input
                  type="email"
                  placeholder="Email"
                  className="form-control rounded-0 border-0 border-bottom border-white"
                  onChange={e => setEmail(e.target.value)}
                />
              </div>
              <div className="mb-3">
                <input
                  type="text"
                  placeholder="Track to tokenize"
                  className="form-control rounded-0 border-0 border-bottom border-white"
                  onChange={e => setTrack(e.target.value)}
                />
              </div>
              <div className="mb-3">
                <p className="mt-4">
                  Please tell us about you, your interest, why BeatBlox and share your social media or whatever you feel like would help our process. Max 400 characters.
                </p>
                <textarea
                  placeholder="Write something"
                  className="form-control rounded-0 border-0 border-bottom border-white"
                  onChange={e => setMessage(e.target.value)}
                />
              </div>
              <button type="submit" className="btn btn-lg btn-outline-light rounded-pill">Submit</button>
              <p className="mt-4">
                We will contacting you soon for further instructions. On the meantime please join our discord or social media:<br/><br/>
                <a href="https://www.instagram.com/thebeatblox/" target="_blank" rel="noreferrer">Instagram</a><br/>
                <a href="https://twitter.com/The_Beatblox" target="_blank" rel="noreferrer">Twitter</a><br/>
                <a href="https://discord.gg/puBEtcKF" target="_blank" rel="noreferrer">Discord</a>
                <br/><br/>
                Thanks for reaching oout and remember to stay on the beat!
              </p>
            </form>
          </div>
        </div>
      </div>
    </div>
  )
}